#!/bin/sh


boot_left_restore(){
		boot_cnt_left=$(fw_printenv -n $1)
		expr $boot_cnt_left + 1 >/dev/null 2>&1 
		if [ $? -eq 0 ] 
		then 
			new_cnt=$(expr $boot_cnt_left + 1)
			if [ $new_cnt > 3 ] 
			then 
				new_cnt=3 
			fi
			fw_setenv "$1" $new_cnt
		else
			fw_setenv "$1" "1"
		fi	

		boot_cnt_left=$(fw_printenv -n $1)

}


check_group(){
	cmdstring=$(cat /proc/cmdline)
	#cmdstring="console=ttyPS0,115200 uio_pdrv_genirq.of_id=generic-uio ${optargs} root=/dev/mmcblk1p3 ro earlyprintk rootfstype=ext4 rootwait rauc.slot=B"
	slot=${cmdstring##*rauc.slot=}
	partnum=${slot:0:1}
	
	if [ "$partnum" = "A" ]
	then
		echo "A Group"
		export CURRENT_GROUP=A
		export SPARE_GROUP=B
		export OPT_PART=/dev/mmcblk1p5
		export OAM_PART=/dev/mmcblk1p7
		boot_left_restore BOOT_A_LEFT 

	elif [ "$partnum" = "B" ]
	then
		echo "B Group"
		export CURRENT_GROUP=B
		export SPARE_GROUP=A
		export OPT_PART=/dev/mmcblk1p6
		export OAM_PART=/dev/mmcblk1p8
		boot_left_restore BOOT_B_LEFT 

	else 
	   return 1
	fi

	echo "CURRENT_GROUP="$CURRENT_GROUP
	echo "SPARE_GROUP="$SPARE_GROUP
	echo "OPT_PART="$OPT_PART
	echo "OAM_PART="$OAM_PART

	return 0
}

case "$1" in
	start)
		echo "mount group" $partnum
		if check_group; then
			mount -t ext4 $OPT_PART /psp
			mount -t ext4 $OAM_PART /oam
			chown -R admin:wheel /psp/
			chown -R admin:wheel /oam/
		else
			echo "Bad Group"
		fi

		;;

	stop)
		echo "umount group" $partnum
		umount -f /psp
		umount -f /oam
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
