#!/bin/sh

case "$1" in
	start)
		/psp/etc/optjointS start
		echo "startup psp applications"
		;;

	stop)
		echo "stop psp applications"
		/psp/etc/optjointK stop
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
